name: Reporte HxH
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restaurar hxh.json a partir do segredo
        run: echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}
      
      - name: Instalar Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exibir hora atual (UTC e São Paulo)
        run: |
          echo "Hora UTC: $(date -u)"
          echo "Hora São Paulo: $(TZ='America/Sao_Paulo' date)"

      - name: Executar o script
        run: python main.py
