name: Reporte HxH

on:
  schedule:
    - cron: '10 * * * *'  # Executa todo horário cheio + 30 min (ex: 01:30, 02:30...)
  workflow_dispatch:      # Permite rodar manualmente pelo GitHub

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout do código
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Instalar dependências
        run: |
          pip install playwright gspread oauth2client pytz
          playwright install chromium

      - name: 🔐 Adicionar credenciais do Google Sheets (hxh.json)
        run: |
          echo "${{ secrets.GSHEET_CRED_JSON }}" > hxh.json

      - name: ▶️ Executar script Python
        run: python seu_script.py
